@startuml

class User {
- userId
- name
- email
- passwordHash
- role
}

class Order {
- orderId
- date
- status
- totalPrice
}

class Carport {
- width
- length
}

class PrefabricatedCarport {
- name
- basePrice
}

class CustomCarport

class Roof {
- price
}

class FlatRoof {
}
class RaisedRoof {
}

class Shed {
- width
- length
}

class MaterialLine {
- quantity
- unitPrice
}

class Material {
- materialId
- name
- price
}

User "has 1 " -- "has 0..*" Order
Order "1" -- "has 1" Carport

Carport "1" -- "has 1" Roof
Carport "1" -- "has 0..1" Shed
Carport "1" -- "has 0..*" MaterialLine
MaterialLine "1" -- "has 1" Material

Carport <|-- "is "PrefabricatedCarport
Carport <|-- "is "CustomCarport

Roof <|-- "is"FlatRoof
Roof <|-- "is"RaisedRoof

@enduml